name: Build Binaries

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        required: true
        default: "1.1.1"
      docker_binaries_for:
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod
        - demo
      environment:
        type: environment

jobs:
  run_docker_container ${{ inputs.docker_tag }}:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Printig variables
      run:  | 
          echo "docker://guarddogai/binaries:" ${{ inputs.docker_tag }}
          echo "repo docker_binaries_:" ${{ inputs.docker_binaries_for }}
        
    - name: Build Binaries for vfido
      uses: docker://guarddogai/binaries:${{ inputs.docker_tag }}
      with:
        args: docker_binaries_${{ inputs.docker_binaries_for }} -it --name binaries 



