name: Build Binaries

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        required: true
        default: "1.1.1"
      docker_binaries_for:
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod
        - demo
      environment:
        type: environment

jobs:
  run_docker_container:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: prinytis
      run: echo "aaaa${{ inputs.docker_tag }}aaa"
        
    - name: Build Binaries for vfido
      uses: docker://guarddogai/binaries:1.1.1
      with:
        args: docker_binaries_${{ inputs.docker_binaries_for }} -it --name binaries 



