name: Build Binaries

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        required: true
        default: 1.1.1
      docker_binaries_for:
        required: true
        default: dev
        type: choice
        options:
        - dev
        - prod
        - demo
      environment:
        type: environment

jobs:
  run_docker_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Build Binaries for vfido
      uses: docker://guarddogai/binaries:${{ inputs.docker_tag }}
      with:
        args: docker_binaries_${{ inputs.dockcer_tag }} -it --name binaries 



