name: Build vfido image

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        required: true
        default: latest
      environment:
        type: environment
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: cloneing
        run: git clone https://oauth2:${{ vars.MARCOTOKEN }}@github.com/guarddog-dev/docker-fido.git

      - name: Build Docker image
        run: |
          cd docker-fido
          docker build  -t guarddogai/vfido:${{ inputs.docker_tag }}  -f dockerfile_prod_alpine .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOKCERNAME }}
          password: ${{ vars.DOCKERPASS }}

      - name: Push Docker image
        run: docker push guarddogai/vfido:${{ inputs.docker_tag }}
